apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos
  namespace: nms4cloud
data:
  # JVM 配置
  JVM_OPTS: "--add-opens java.base/java.lang=ALL-UNNAMED"

  # SkyWalking APM 配置
  SW_AGENT_COLLECTOR_BACKEND_SERVICES: "skywalking:11800"

  # 时区配置
  TZ: "Asia/Shanghai"

  # Nacos 配置中心配置
  spring.cloud.nacos.config.namespace: "56a75109-dbdc-4c5a-8fc1-b2300cef7f4a"
  spring.cloud.nacos.config.server-addr: "nacos:8848"

  # Nacos 服务发现配置
  spring.cloud.nacos.discovery.server-addr: "nacos:8848"
